"use client";

import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowRight, Compass, Layers, Zap, Globe, Heart, Shield, Star, MessageSquare, Code } from "lucide-react";
import Image from "next/image";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen relative overflow-hidden bg-background selection:bg-primary selection:text-primary-foreground">
      
      {/* Subtle Grid Background */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] -z-10" />

      {/* 1. HERO SECTION */}
      <section className="flex flex-col items-center justify-center pt-32 pb-20 px-6 text-center z-10 w-full max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-card-border bg-card/80 backdrop-blur-md mb-8 text-xs font-semibold tracking-wide uppercase text-muted-foreground shadow-sm hover:bg-card transition-colors cursor-pointer"
        >
          <Zap className="w-3.5 h-3.5 text-primary" />
          <span>Travel DNA Engine is live</span>
        </motion.div>

        <motion.h1 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
          className="text-5xl md:text-8xl font-extrabold tracking-tight text-foreground mb-8 leading-[1.05]"
        >
          Travel intuitively.<br/>
          <span className="text-muted-foreground">Generated by AI.</span>
        </motion.h1>

        <motion.p 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
          className="text-lg md:text-2xl text-muted-foreground mb-12 max-w-2xl font-medium leading-relaxed"
        >
          Most planners ask where you&apos;re going. We ask who you are. 
          Experience dynamic, hyper-personalized itineraries designed exclusively for your psychological travel profile.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
          className="flex flex-col sm:flex-row gap-4"
        >
          <Link href="/quiz">
            <button className="group relative inline-flex items-center justify-center gap-3 px-8 py-4 font-semibold text-primary-foreground bg-primary rounded-full hover:opacity-90 transition-all duration-300 shadow-[0_4px_14px_0_rgba(0,0,0,0.1)] hover:shadow-[0_6px_20px_rgba(0,0,0,0.15)] hover:-translate-y-0.5 w-full sm:w-auto">
              <span>Discover Your DNA</span>
              <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
            </button>
          </Link>
          <Link href="#features">
            <button className="inline-flex items-center justify-center gap-3 px-8 py-4 font-semibold text-foreground bg-card border border-card-border rounded-full hover:bg-muted transition-all duration-300 w-full sm:w-auto">
              <span>See How It Works</span>
            </button>
          </Link>
        </motion.div>
      </section>

      {/* 2. IMAGE SHOWCASE SECTION */}
      <section className="w-full max-w-7xl mx-auto px-6 py-20 z-10">
        <motion.div 
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 1, ease: [0.16, 1, 0.3, 1] }}
          className="grid grid-cols-1 md:grid-cols-3 gap-6"
        >
          <div className="relative h-[400px] md:h-[500px] rounded-3xl overflow-hidden group">
            <Image src="https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&q=80&w=1000" alt="Cultural Explorer" fill className="object-cover transition-transform duration-700 group-hover:scale-105" />
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
            <div className="absolute bottom-0 left-0 p-8">
              <div className="px-3 py-1 bg-white/20 backdrop-blur-md rounded-full text-white text-xs font-bold uppercase tracking-wider mb-3 w-fit">The Cultural Explorer</div>
              <h3 className="text-white text-2xl font-bold">Paris, France</h3>
            </div>
          </div>
          <div className="relative h-[400px] md:h-[500px] rounded-3xl overflow-hidden group">
            <Image src="https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&q=80&w=1000" alt="Adventure Nomad" fill className="object-cover transition-transform duration-700 group-hover:scale-105" />
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
            <div className="absolute bottom-0 left-0 p-8">
              <div className="px-3 py-1 bg-white/20 backdrop-blur-md rounded-full text-white text-xs font-bold uppercase tracking-wider mb-3 w-fit">The Adventure Nomad</div>
              <h3 className="text-white text-2xl font-bold">Patagonia, Chile</h3>
            </div>
          </div>
          <div className="relative h-[400px] md:h-[500px] rounded-3xl overflow-hidden group">
            <Image src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1000" alt="Luxury Escapist" fill className="object-cover transition-transform duration-700 group-hover:scale-105" />
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />
            <div className="absolute bottom-0 left-0 p-8">
              <div className="px-3 py-1 bg-white/20 backdrop-blur-md rounded-full text-white text-xs font-bold uppercase tracking-wider mb-3 w-fit">The Luxury Escapist</div>
              <h3 className="text-white text-2xl font-bold">Maldives</h3>
            </div>
          </div>
        </motion.div>
      </section>

      {/* 3. FEATURES SECTION */}
      <section id="features" className="w-full bg-muted/30 py-32 border-y border-card-border z-10 mt-20">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-20">
            <h2 className="text-3xl md:text-5xl font-bold text-foreground tracking-tight mb-4">Intelligence built for travel.</h2>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">Every itinerary is specifically mapped to your behavioral profile, avoiding generic tourist traps and finding what moves you.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="glass-panel p-10 rounded-3xl flex flex-col items-start text-left bg-card hover:shadow-lg transition-all duration-300">
              <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-6">
                <Compass className="w-6 h-6 text-primary" />
              </div>
              <h3 className="text-xl font-bold text-foreground mb-3">Behavioral Analysis</h3>
              <p className="text-muted-foreground leading-relaxed">We map your unique psychological archetype across 6 dimensions to find experiences that resonate with your core identity.</p>
            </div>

            <div className="glass-panel p-10 rounded-3xl flex flex-col items-start text-left bg-card hover:shadow-lg transition-all duration-300">
              <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-6">
                <Globe className="w-6 h-6 text-primary" />
              </div>
              <h3 className="text-xl font-bold text-foreground mb-3">Hidden Gem Discovery</h3>
              <p className="text-muted-foreground leading-relaxed">Powered by Gemini 1.5, we actively filter out tourist traps and source hyper-local, underrated locations.</p>
            </div>

            <div className="glass-panel p-10 rounded-3xl flex flex-col items-start text-left bg-card hover:shadow-lg transition-all duration-300">
              <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-6">
                <Layers className="w-6 h-6 text-primary" />
              </div>
              <h3 className="text-xl font-bold text-foreground mb-3">Adaptive Intelligence</h3>
              <p className="text-muted-foreground leading-relaxed">Sudden rain? Feeling tired? Inject real-world variables and watch the entire timeline shift dynamically in seconds.</p>
            </div>
          </div>
        </div>
      </section>

      {/* 4. FOOTER */}
      <footer className="w-full bg-background border-t border-card-border pt-16 pb-8 z-10">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-12 md:gap-8 mb-16">
            <div className="col-span-1 md:col-span-2">
              <div className="flex items-center gap-2 mb-4">
                <Zap className="w-5 h-5 text-primary" />
                <span className="font-bold text-xl tracking-tight text-foreground">Travel DNA</span>
              </div>
              <p className="text-muted-foreground max-w-sm">
                Redefining the way we explore the world through artificial intelligence and behavioral psychology.
              </p>
            </div>
            
            <div>
              <h4 className="font-semibold text-foreground mb-4">Product</h4>
              <ul className="space-y-3 text-muted-foreground text-sm">
                <li><Link href="/quiz" className="hover:text-primary transition-colors">DNA Assessment</Link></li>
                <li><Link href="#" className="hover:text-primary transition-colors">Adaptive Itineraries</Link></li>
                <li><Link href="#" className="hover:text-primary transition-colors">Pricing</Link></li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-semibold text-foreground mb-4">Connect</h4>
              <ul className="space-y-3 text-muted-foreground text-sm">
                <li><Link href="#" className="flex items-center gap-2 hover:text-primary transition-colors"><MessageSquare className="w-4 h-4"/> Twitter</Link></li>
                <li><Link href="#" className="flex items-center gap-2 hover:text-primary transition-colors"><Code className="w-4 h-4"/> GitHub</Link></li>
                <li><Link href="#" className="flex items-center gap-2 hover:text-primary transition-colors"><Heart className="w-4 h-4"/> Built with Love</Link></li>
              </ul>
            </div>
          </div>
          
          <div className="flex flex-col md:flex-row items-center justify-between pt-8 border-t border-card-border text-sm text-muted-foreground">
            <p>© {new Date().getFullYear()} Travel DNA. All rights reserved.</p>
            <div className="flex items-center gap-6 mt-4 md:mt-0">
              <Link href="#" className="hover:text-foreground transition-colors">Privacy Policy</Link>
              <Link href="#" className="hover:text-foreground transition-colors">Terms of Service</Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
